# Generated by Django 4.2.1 on 2023-07-01 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='id ususario')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('numero', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfilt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_user', models.CharField(max_length=100)),
                ('edad_user', models.PositiveIntegerField()),
                ('foto_user', models.ImageField(upload_to='fotos/')),
                ('descripcion_user', models.TextField()),
                ('nombre_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked', models.BooleanField(default=False)),
                ('disliked', models.BooleanField(default=False)),
                ('matched_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_by', to='core.perfilt')),
                ('nombre_user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.perfilt')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibido', to='core.perfilt')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviado', to='core.perfilt')),
            ],
        ),
    ]
